### ISSUE TITLE
RTX 3XXX series not supported

### ISSUE THREAD

**Issue by 78Alpha** [compphoto/BoostingMonocularDepth#15]
Thought to give my new GPU test on this mixed with 3DP but noticed some suspicious slowness, a process that should have taken 10 minutes was taking 7 hours. I worked down the list of why and thought to test this on its own, and sure enough, it provided the information I needed. It gives a warning that the RTX 3070 in my system has a newer compute version than is supported, and instead of defaulting to my RTX 2060 (this is supported and works in seconds), it defaults to a single CPU thread (1/16).

The same issue is found in 3DP and I'll have to forward the issue there too.

`conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge `

on the pytorch page makes the card work and the results are not altered by the change

**Comment by miangoleh** [comment]
Thanks for sharing. 
cudatoolkit version or GPU model should not affect the method (You can increase GPU limit specified by a variable in code if you have stronger GPU) and the suggestion of cudatookit 10.2 with python 3.7 is only because it leads to correct dependencies for running midas and Leres. I'll try to change the explanation and make it more clear to prevent further concerns.  
Our mergnet is trained with torch 0.4 to be compatible with versions >=0.4

**Comment by miangoleh** [comment]
Closed due to inactivity.
