### ISSUE TITLE
LeReS shape recovery with boosted depth

### ISSUE THREAD

**Issue by fmu2** [compphoto/BoostingMonocularDepth#25]
Thanks for the great work! Is it still possible to use the boosted depth for shape recovery as in the original LeReS work? It looks like the output of base depth model goes through several normalization steps before merging.

**Comment by miangoleh** [comment]
Hi. We haven't specifically tried that so unfortunately, I don't have any useful insight to provide. But I am positive toward testing that because it might just work!

I just have to add that the normalization is only to make the merging possible and they are not changing the characteristics of the results but our results having much more high-frequency details might make it hard for the shape recovery to perform equal to original LeRes.

**Comment by fmu2** [comment]
Thanks for your prompt reply. It turns out that the raw boosted depth is not quite compatible with the shift and focal length regression models from LeReS. However, shape recovery seems to work after I calibrate the boosted depth using the coarse depth from LeReS's depth estimation model.

**Comment by miangoleh** [comment]
Thanks for sharing your observation. I would be thankful if you could share some results with me.
