### ISSUE TITLE
Midas not running

### ISSUE THREAD

**Issue by Joff1000** [compphoto/BoostingMonocularDepth#26]
Hallo, firstly thanks for the great work.
I have been running mainly Midas in Google Colab with great success, but today it won't run and throws up this error
FileNotFoundError: [Errno 2] No such file or directory: 'midas/model.pt'

Leres runs fine, but for some reason, I can't get it to run Midas, any ideas?
Thanks

**Comment by miangoleh** [comment]
This might be happening because downloading midas model weight is interrupted or failed. 
I suggest resetting the Colab run engine and try to rerun the code. (from the top menu bar select Runtime/Factory reset runtime)

To make sure if the model weights file is downloaded you can check /content/BoostingMonocularDepth/midas directory for midas.pt file before running "Code section 3".

**Comment by Joff1000** [comment]
Thanks for that information, it's a big help.
Cheers
