### ISSUE TITLE
Confused about the gtfake and mergenet?

### ISSUE THREAD

**Issue by JiaDingCN** [compphoto/BoostingMonocularDepth#31]
Hi, I'm reading your exciting paper and code, but I get a little confused about the mergenet part.
1. It seems that the depth ground truth when training the mergenet is generated by passing the image data in `$root_dir/ibims1/rgb` and `$root_dir/middleburry/rgb` to a pretrained MiDas, and use a matlab file(create_crops.m) to save the results in gt_fake_result_dir. But the inner data, which is used as the input of the mergenet, is also made by the same pretrained midas network with the same resolution, so what makes the gtfake more accurate than the inner?
2. It seems the mergenet has two different functions: merge the whole-image estimations with low and high resolutions and merge the base estimate(whole-image estimation) and the patch estimate(estimation of a part of the image). Is that right?

**Comment by miangoleh** [comment]
Hi. 

1.
The difference is the sequence of creating patches and estimation. 
To generate the ground_truth fake; First, we are estimating the whole RGB image's depth and then create patches out of the estimated depth(although we are using a higher resolution than default Midas we made sure estimations are consistent in terms of overall depth structure to be used as fake ground truth). 
The inner data is generated the opposite way. First, we are creating patches and then feeding them to the Midas. This way we will have much more details but the results will have inconsistent overall structure.
inner data is generated the same way as ground truth fake but at the default Midas resolution.

This way and by using some filtering tricks we are able to mimic the characteristics of data we need to train a depth merge operation. I recommend reading the supplementary material as we are discussing the process of dataset generation and filtering in more detail. 

2. Mergenet has one function: Merging details (high frequencies) to a base(low frequency) depth map. This functionality can be used for both double estimation and merging patches to the base process since in both cases there is a low frequency and a high-frequency depth that we want to merge. (Low/High estimates for double estimation and Base/Patch for the latter).
