### ISSUE TITLE
different color range of depth image

### ISSUE THREAD

**Issue by mahdis-sa** [compphoto/BoostingMonocularDepth#33]
Hi, 
I faced a problem during checking both LeRes and MiDas output of this command: 
python run.py --colorize_results --Final --data_dir PATH_TO_INPUT --output_dir PATH_TO_RESULT --depthNet #[0,1 or 2]

The color range of output images is different during running depthNet 0 and 2 separately. see below please: 
I would appreciate it if you could guide me on why this happened? it seems the colors become opposite and it affects the evaluation result, too. 

![image](https://user-images.githubusercontent.com/51942105/135838089-b5fe3397-03c5-425b-b458-f1b8ae1b88c9.png)

**Comment by miangoleh** [comment]
--colorize_results is only for visualization purposes. You should never use it for result generation before evaluation. Run the command without this argument variable to get 16-bit grayscale png files to evaluate. 

LeRes is estimating depth and MiDas is estimating disparity (inverse-depth). That's why they are different.

**Comment by mahdis-sa** [comment]
Thank you @miangoleh, now I got it. 
I'm a bit new in this field and I have another question: 
In the "Evaluation" section: what is the unit of evaluation error? for example, you gotta RMSE = 0.1557 for MiDaS, is that in cm or mm?  how we can change it within a code?
