### ISSUE TITLE
Evaluate prediction depth on KITTI dataset using evaluatedataset.m

### ISSUE THREAD

**Issue by Oreobun** [compphoto/BoostingMonocularDepth#47]
I have a doubt about the evaluation of prediction results on the KITTI dataset. I tried to get the depth estimation of a particular image from the KITTI dataset and observe the result using a simple python code as shown below. The prediction is done using depthNet = 2 (The LeReS model)

`depth_gt = Image.open(path)`
 `depth_gt = np.asarray(depth_gt, dtype=np.float32)`

I printed the result and observe that the "pixel" value of the image is of range [0, 65535], and the ground truth returns a range of [0, 255]. I mainly want to know the ORD error of the image, may I know if there is any image transformation before I do the evaluation? Or I could provide the directory path into 
`estimation_path = '';`
`gt_depth_path = '';`
from evaluatedataset.m and get the ORD error directly.

To be more specific the prediction depth map obtained from boosting monocular technique, followed by the ground truth and the original RGB are below. Should I rescale the range of the depth map? or I should perform normalization on both of the images before conducting the evaluation.
![0000000069(pred)](https://user-images.githubusercontent.com/55806893/146499938-5d37b7d3-4561-4463-98c9-53a12d0c2c56.png)
![0000000069](https://user-images.githubusercontent.com/55806893/146499959-5ef98304-d4c5-48e8-a144-c27a628ac51e.png)
![0000000069(rgb)](https://user-images.githubusercontent.com/55806893/146499969-c5e61d74-59ec-41e2-9ed9-d39aea3cf536.png)

Edit: I notice the difference in the "pixel" value is due to a different data type used to represent the image. Some images use float32 to represent their image and the values are in mm while others could be represented by uint8. My question now is how do I use the evaluation code in this case? I am currently doing testing on the [DIODE](https://diode-dataset.org/) dataset by scaling the ground truth & prediction depth map into uint8 representation before evaluation. Would really like to know if I am doing this correctly.

**Comment by miangoleh** [comment]
The range is [0, 65535] because the resulting png files are 16-bit integers.

I believe the script included in evaluate_dataset.m already rescales both predictions and ground truth to the range of [0,1]

Kitti has a sparse ground truth depth map. D3R expects a dense ground truth as its relying on ground truth superpixels. So its values are invalid. Regarding other metrics, make sure that the invalid values in the ground truth should be included in the invalid mask and excluded from evaluation. We did not design our test script for sparse datasets like KITI. You may need to edit the script to get reliable results.
