### ISSUE TITLE
How to align estimated depth with GT depth?

### ISSUE THREAD

**Issue by zParquet** [compphoto/BoostingMonocularDepth#68]
How can I align estimated depth with GT depth? Are the depths or inversed depths obey linear transformation with GT depths? 

For example, I got an output depth map using LeRes backbone as following:

![DSC07957](https://github.com/compphoto/BoostingMonocularDepth/assets/42182507/0c6a4206-cdc6-457d-b998-aa5ebd4a1eda)

![DSC07957_down4 JPG](https://github.com/compphoto/BoostingMonocularDepth/assets/42182507/768ad3e9-ee2f-4701-8246-dee54ba19817)

The depth map looks pretty good. I tried to reproject the depth map into 3D space. 

To  eliminate the disalignment, I transform the output depth map D to align the predicted depth from SFM(regarded as GT depth) D' using `D'=D*scale+shift`. However, the point cloud shows large artifacts:

![image](https://github.com/compphoto/BoostingMonocularDepth/assets/42182507/2ce50c77-856c-447c-b856-f65209918058)

Do you have any idea of this problem? Or what I want to ask is, can we use linear transformation (for LeRes) to align the output depth with GT depth?

Thanks!

**Comment by miangoleh** [comment]
Since our model incorporates the details via a gradient transfer operation (look at how our merging network is trained) the output is only accurate up to ordinal depth relations (pixel A is farther or closer to the camera than pixel B). Hence finding the scale and shift will not generate an accurate 3D scene.
