### ISSUE TITLE
Questions about code.

### ISSUE THREAD

**Issue by xiong-jie-y** [compphoto/BoostingMonocularDepth#7]
Hi, thank you for exciting model!

I'm trying to understand the code to implement it in other language.
I have some questions about the code. 

1. The Interpolation method used for resize operation throughout the code are INTER_CUBIC, is it better than other interpolation methods for your method?
2. When doing double estimate, monocular depth estimation output is firstly resized to original image size and then resized to pix2pix model input size. Should the monocular depth estimation output be resized to pix2pix model directly? Is there performance difference between them?
3. Why is [the line](https://github.com/compphoto/BoostingMonocularDepth/blob/8b2b18f3416d50151a4753a42020f63799515825/run.py#L359) necessary?
4. Why is [the line](https://github.com/compphoto/BoostingMonocularDepth/blob/8b2b18f3416d50151a4753a42020f63799515825/run.py#L205) use `patch_whole_estimate_base` instead of `patch_whole_estimate_updated`?

**Comment by miangoleh** [comment]
Hi.

1- We used the INTER_CUBIC because it's recommended but there is no specific reason for it. But for resizing happening in "calculateprocessingres" should be exactly the same since other methods might highly affect the edge maps.  

2- This is only to make the code easier to interpret (I've used the Midas-v2 repo for the forward path on midas). There is no specific reason to resize it back to the original resolution. 

3- Merge net networks architecture gets input in the range [-1,1] and generates the results also in the same range. That is to map the results to [0,1]. 

4- There is no "patch_whole_estimate_updated" variable in our most recent version. Please consider updating your local version. But the difference was to use the updated base or original base to merge each patch onto. We noticed merging onto the updated base might generate inconsistent results.

**Comment by xiong-jie-y** [comment]
Hi!

Thank you for polite and detail answers! :smile:
