### ISSUE TITLE
Details about the provided checkpoint

### ISSUE THREAD

**Issue by nandometzger** [compphoto/BoostingMonocularDepth#75]
Thank you so much for the work and also including downloadable checkpoints.

Could you give some background how those models were trained since you used two datasets in you paper. Is it trained on Middlebury 2024, or IBims, or both together?

Thanks :)

**Comment by miangoleh** [comment]
Hi.

Our merge model is trained on mixture of images from both datasets and their estimated depth from MiDaS. (instructions can be found [here](https://github.com/compphoto/BoostingMonocularDepth/blob/main/dataset_prepare/mergenet_dataset_prepare.md))

Due to the low-level nature of the merging operation (i.e. learning based gradient transfer operation) experiments show that our merging network generalizes to different datasets and in the wild photos generated from different base depth estimation networks (MiDaS, SGR, LeReS). 

You can find a more detailed explanation of the dataset generation and training process of the merging network in my [Master's Thesis](https://yaksoy.github.io/bmd-msc/) and [presentation](https://www.youtube.com/watch?v=DZ0ft1l50KY
).



In addition in our [recently published siggraph paper](https://github.com/compphoto/sidepth) which is inspired from this work, we provide a new boostable depth estimation network and a refined version of our merge network that is trained using more datasets for better robustness.

**Comment by miangoleh** [comment]
You can find a more detailed explanation of the dataset generation and training process of the merging network in my Master's Thesis and my presentation. 

https://yaksoy.github.io/bmd-msc/
https://www.youtube.com/watch?v=DZ0ft1l50KY

**Comment by nandometzger** [comment]
thank you for the detailed answer!
